# Generated by Django 2.1.5 on 2019-01-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=250)),
                ('release_date', models.CharField(max_length=50)),
                ('video_release_date', models.CharField(max_length=50)),
                ('IMDB_URL', models.CharField(max_length=450)),
                ('unknown', models.IntegerField(default=0)),
                ('Action', models.IntegerField(default=0)),
                ('Adventure', models.IntegerField(default=0)),
                ('Animation', models.IntegerField(default=0)),
                ('Children', models.IntegerField(default=0)),
                ('Comedy', models.IntegerField(default=0)),
                ('Crime', models.IntegerField(default=0)),
                ('Documentary', models.IntegerField(default=0)),
                ('Drama', models.IntegerField(default=0)),
                ('Fantasy', models.IntegerField(default=0)),
                ('Film_Noir', models.IntegerField(default=0)),
                ('Horror', models.IntegerField(default=0)),
                ('Musical', models.IntegerField(default=0)),
                ('Mystery', models.IntegerField(default=0)),
                ('Romance', models.IntegerField(default=0)),
                ('Sci_Fi', models.IntegerField(default=0)),
                ('Thriller', models.IntegerField(default=0)),
                ('War', models.IntegerField(default=0)),
                ('Western', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movielens.Item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movielens.User')),
            ],
        ),
    ]
