# Generated by Django 2.1.5 on 2019-02-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FilePathField(path='/Users/chris/projects/personalens/static/img')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movielens.Item')),
            ],
        ),
    ]
