# Generated by Django 2.1.5 on 2019-02-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielens', '0002_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='movie_id',
            new_name='item',
        ),
    ]
