# Generated by Django 2.1.5 on 2019-02-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielens', '0003_auto_20190204_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
